CLASS zdj_class_01 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS get_data.
    METHODS insert_data.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zdj_class_01 IMPLEMENTATION.
  METHOD get_data.
  ENDMETHOD.
    METHOD insert_data.
  ENDMETHOD.
ENDCLASS.
